---
title: "Learn Bayesian Linear Models in R"
---

This is the website of the workshop **learnBayes**.

Please, check the [Set-up](setup.qmd) page for important set-up instructions, before joining the workshop.

This workshop assumes you have a **solid command of R and tidyverse packages, and familiarity with linear modelling** (including interpreting coefficients and interactions, running linear models with binomial/Bernoulli family, aka logistic regression).

If you wish to revise any of these topics, we recommend the following resources:

- [R for Data Science](https://r4ds.had.co.nz) (online book).
- [Statistics for Linguists in R](https://www.routledge.com/Statistics-for-Linguists-An-Introduction-Using-R/Winter/p/book/9781138056091) (texbook).

### Download the materials

All the materials of the workshop (data, code, slides) are in the workshop [repository](https://github.com/stefanocoretta/learnBayes) on GitHub.

You have two options:

1. You can fork the repository and clone it locally if you use git/GitHub.

2. You can simply download the repo by clicking on the `Code` button > `Download ZIP` on GitHub.

The repo is an RStudio project. Before opening the project (by double-clicking on the `learnBayes.Rproj` file), you should delete the `.Rprofile` file if you don't use [renv](https://rstudio.github.io/renv/index.html) (renv is an R environment manager) to disable renv.
