---
title: "Pre-workshop set-up"
editor: visual
---

Please, follow these instructions carefully to get ready **at least one day before the workshop**.

::: callout-important
Installing the necessary software takes a lot of space on your computer and can take a long of time (1-3 hours depending on the system).
:::

## Pre-requisites

Before installing the necessary software, make sure you have installed or updated the following software.

-   The **latest version of R** (<https://cloud.r-project.org>).

-   The **latest version of RStudio** (<https://www.rstudio.com/products/rstudio/download/#download>).

-   Your **operating system is up-to-date**.

## Starter Kit

I strongly recommend you to use the Starter Kit.

You can get the Starter Kit from [here](https://github.com/stefanocoretta/learnBayesKit). It is just an RStudio project with some useful files.

## Installation

::: {.callout-important icon="false"}
If you have previously installed the C++ toolkit, CmdStan and/or cmdstanr, or if you have recently updated your OS, please follow these instructions to reinstall them.
:::

Now you will need to install a few packages and extra software.

Here is an overview of what you will install:

1.  C++ toolchain.

2.  R packages: tidyverse, remotes, cmdstanr, brms.

3.  CmdStan (including Stan).

### 1. Install the C++ toolchain

Some of the software (CmdStan) used in the workshop requires a working C++ toolchain for compilation.

You can find information on how to set up the C++ toolchain in [Section 1.2.1](https://mc-stan.org/docs/cmdstan-guide/cmdstan-installation.html#cpp-toolchain) of the CmdStan User's Guide.

Make sure to follow the instructions for your operating system.

::: callout-caution
**WINDOWS USERS**: The installation process for Windows is more complex than that on Unix/macOS, so pay extra attention in reading the instructions.

Many attendants with a Windows laptop forget to follow some of the steps (in particular, make sure you are updating the PATH variable as instructed).
:::

### 2. Install the R packages

You need to install the following packages:

``` r
install.packages(c("tidyverse", "remotes"))
remotes::install_github("stan-dev/cmdstanr")
install.packages(c("brms"))
install.packages(c("tidybayes", "extraDistr"))
```

The [cmdstanr](https://mc-stan.org/cmdstanr/index.html) package is an interface between R and CmdStan (see below), while [brms](https://paul-buerkner.github.io/brms/) is the package you will use to run Bayesian linear models (think of it as the Bayesian equivalent of [lme4](https://github.com/lme4/lme4)).

It will take several minutes to install the packages, depending on your system and configuration.

**If after opening the Starter Kit in RStudio you get asked to install extra packages or software, please do so.**

### 3. Install CmdStan

Now that you have installed the R packages, you need to install CmdStan.

[CmdStan](https://mc-stan.org/users/interfaces/cmdstan) is a shell interface to the programming language Stan.

[Stan](https://mc-stan.org) is what runs the Bayesian models, but you don't have to know Stan, because you will use the R packages to run the models (those packages will communicate with Stan in your stead).

To install CmdStan, run the following command in the R console:

``` r
cmdstanr::install_cmdstan(cores = parallel::detectCores(), overwrite = TRUE)
```

### Check your installation

Run the following in the RStudio Console.

``` r
library(cmdstanr)
file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(file, force_recompile = TRUE)
data_list <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))
fit <- mod$sample(
  data = data_list, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500 # print update every 500 iters
)
```

If everything goes well you should see `Compiling Stan program…` and then `Running MCMC with 4 parallel chains…` followed by information on chains and iterations.

## Troubleshoot

If you have issues with any of these steps, please get in touch with Stefano.
