{
  "hash": "e4d2eddf8ad745d5f461141654cd506d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduction to Bayesian regression models\"\nsubtitle: \"02 - Bayesian regression\"\nauthor: \"Stefano Coretta\"\ninstitute: \"University of Edinburgh\"\neditor: source\nformat:\n  mono-light-revealjs:\n    theme: [default, custom.scss]\n    history: false\n    preview-links: true\nfilters:\n  - tachyonsextra\nexecute: \n  echo: true\nbibliography: references.bib\n---\n\n\n\n## Regression models\n\n::: box-note\n-   Simplest regression model:\n\n$$\ny \\sim \\beta_0 + \\beta_1 \\cdot x\n$$\n\n-   where $y$ and $x$ are numeric variables.\n\n-   <https://stefanocoretta.shinyapps.io/lines/>\n:::\n\n## MALD\n\n::: box-tip\n**Does the mean phone-level distance affect reaction times**?\n:::\n\n. . .\n\n::: box-note\n-   Mean phone-level distance is a proxy of word \"uniqueness\".\n\n-   More unique words should take longer to recognise as real words because there are less competitors (i.e. similar words) that can have a facilitatory effect on recognition.\n:::\n\n## MALD: `RT` and `PhonLev`\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Scatter plot of mean phone-level distance vs reaction times.](02_regression_files/figure-revealjs/fig-dist-stat-1.png){#fig-dist-stat width=960}\n:::\n:::\n\n\n## MALD: regression\n\n$$\nRT \\sim \\beta_0 + \\beta_1 \\cdot \\text{PhonLev}\n$$\n\n. . .\n\nor\n\n$$\n\\begin{align}\nRT & \\sim \\beta_0 + \\beta_1 \\cdot \\text{PhonLev} + \\epsilon\\\\\n\\epsilon & \\sim Gaussian(0, \\sigma)\n\\end{align}\n$$\n\n. . .\n\nor\n\n$$\n\\begin{align}\nRT & \\sim Gaussian(\\mu, \\sigma)\\\\\n\\mu & = \\beta_0 + \\beta_1 \\cdot \\text{PhonLev}\\\\\n\\end{align}\n$$\n\n::: box-note\nThe model estimates the posterior probability distributions of $\\beta_0, \\beta_1, \\sigma$.\n:::\n\n## \n\n```{=html}\n<iframe allowfullscreen frameborder=\"0\" height=\"100%\" mozallowfullscreen style=\"min-width: 500px; min-height: 355px\" src=\"https://app.wooclap.com/events/JEJPPA/questions/68346b14678ad4313b2e2b05\" width=\"100%\"></iframe>\n```\n\n## MALD: regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrm_lev <- brm(\n  RT ~ 1 + PhonLev,\n  data = mald,\n  family = \"gaussian\",\n  file = \"./data/cache/brm_lev.rds\",\n  chains = 4, \n  iter = 2000,\n  cores = 4\n)\n\nsummary(brm_lev)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: RT ~ 1 + PhonLev \n   Data: mald (Number of observations: 3000) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept   861.62     35.11   793.25   929.05 1.00     4139     2815\nPhonLev      26.05      4.85    16.70    35.40 1.00     4169     2866\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma   345.95      4.54   337.09   354.71 1.00     3849     2919\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n## Interpret the summary: `Intercept`\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept   861.62     35.11   793.25   929.05 1.00     4139     2815\nPhonLev      26.05      4.85    16.70    35.40 1.00     4169     2866\n```\n\n\n:::\n:::\n\n\n::: box-warning\n`Intercept` is $\\beta_0$.\n\n-   $\\beta_0$ is the expected mean RT when `PhonLev` is 0.\n\n-   The posterior probability distribution of $\\beta_0$ is $\\mathcal{P}(862, 35)$.\n\n-   There is a **95% probability** that the mean RTs when `PhonLev` is 0 is **between 793 and 929 ms**, conditional on the model and data. This is the 95% Credible Interval (CrI) of $\\mathcal{P}(862, 35)$.\n:::\n\n## Interpret the summary: `PhonLev`\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept   861.62     35.11   793.25   929.05 1.00     4139     2815\nPhonLev      26.05      4.85    16.70    35.40 1.00     4169     2866\n```\n\n\n:::\n:::\n\n\n::: box-warning\n`PhonLev` is $\\beta_1$.\n\n-   $\\beta_1$ is the expected difference in RT *for each unit change* of `PhonLev`.\n\n-   The posterior probability distribution of $\\beta_1$ is $\\mathcal{P}(26, 5)$.\n\n-   There is a **95% probability** that each unit change of `PhonLev` corresponds to a change in mean RT **between +17 and +35 ms**, conditional on the model and data. This is the 95% Credible Interval (CrI) of $\\mathcal{P}(26, 5)$.\n:::\n\n## \n\n```{=html}\n<iframe allowfullscreen frameborder=\"0\" height=\"100%\" mozallowfullscreen style=\"min-width: 500px; min-height: 355px\" src=\"https://app.wooclap.com/events/JEJPPA/questions/6841e1577066f550294b8926\" width=\"100%\"></iframe>\n```\n\n## Effect of `PhonLev` on RTs\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_effects(brm_lev, \"PhonLev\")\n```\n\n::: {.cell-output-display}\n![Predicted effect of mean phone-level distance on RTs from a Bayesian regression model.](02_regression_files/figure-revealjs/fig-brm-lev-1.png){#fig-brm-lev width=960}\n:::\n:::\n\n\n## MCMC draws\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrm_lev_draws <- as_draws_df(brm_lev)\n\nbrm_lev_draws\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A draws_df: 1000 iterations, 4 chains, and 6 variables\n   b_Intercept b_PhonLev sigma Intercept lprior   lp__\n1          878        25   344      1054    -13 -21803\n2          880        25   345      1056    -13 -21803\n3          872        25   340      1050    -13 -21803\n4          821        32   341      1047    -13 -21803\n5          838        30   344      1054    -13 -21803\n6          859        25   352      1037    -13 -21803\n7          861        25   350      1039    -13 -21803\n8          861        28   348      1057    -13 -21803\n9          916        20   346      1056    -13 -21804\n10         844        29   350      1052    -13 -21803\n# ... with 3990 more draws\n# ... hidden reserved variables {'.chain', '.iteration', '.draw'}\n```\n\n\n:::\n:::\n\n\n## Predicted RTs at representative values of `PhonLev`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(mald$PhonLev)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  5.608767 14.186571\n```\n\n\n:::\n\n```{.r .cell-code}\nbrm_lev_draws <- brm_lev_draws |> \n  mutate(\n    # RTs when PhonLev is 5\n    rt_05 = b_Intercept + b_PhonLev * 5,\n    # RTs when PhonLev is 10\n    rt_10 = b_Intercept + b_PhonLev * 10,\n    # RTs when PhonLev is 15\n    rt_15 = b_Intercept + b_PhonLev * 15,\n  )\n\nbrm_lev_draws |> \n  select(rt_05, rt_10, rt_15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4,000 × 3\n   rt_05 rt_10 rt_15\n   <dbl> <dbl> <dbl>\n 1 1002. 1127. 1251.\n 2 1004. 1128. 1252.\n 3  998. 1123. 1249.\n 4  980. 1140. 1299.\n 5  990. 1142. 1293.\n 6  985. 1111. 1236.\n 7  987. 1112. 1238.\n 8  999. 1138. 1276.\n 9 1015. 1113. 1211.\n10  990. 1137. 1284.\n# ℹ 3,990 more rows\n```\n\n\n:::\n:::\n\n\n## Predicted RTs at representative values of `PhonLev`: plot\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nlibrary(ggdist)\n\nbrm_lev_draws |> \n  select(rt_05, rt_10, rt_15) |> \n  \n  # Pivot so to make plotting easier\n  pivot_longer(everything()) |> \n  # Pivot creates a name column with values `rt_05, rt_10, rt_15`\n  # and a value column with the draws values\n  \n  ggplot(aes(value, name)) +\n  # Stat halfeye from ggdist\n  stat_halfeye() +\n  labs(\n    caption = \"Point = median, thick line = 66% CrI, thin line = 95% CrI.\"\n  )\n```\n\n::: {.cell-output-display}\n![Predicted RTs at representative values of mean phon-level distance.](02_regression_files/figure-revealjs/fig-lev-5-10-15-1.png){#fig-lev-5-10-15 width=960}\n:::\n:::\n\n\n## Calculating CrIs from the draws\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(posterior)\n\nbrm_lev_cri <- brm_lev_draws |> \n  select(rt_05, rt_10, rt_15) |> \n  pivot_longer(everything()) |> \n  group_by(name) |> \n  summarise(\n    # Use quantile2() from posterior package\n    lo_95 = round(quantile2(value, 0.025)),\n    hi_95 = round(quantile2(value, 0.0975))\n  )\n\nbrm_lev_cri\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  name  lo_95 hi_95\n  <chr> <dbl> <dbl>\n1 rt_05   968   976\n2 rt_10  1092  1103\n3 rt_15  1177  1203\n```\n\n\n:::\n:::\n\n\n## Width of the CrIs\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrm_lev_cri |> \n  mutate(\n    cri_width = hi_95 - lo_95\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  name  lo_95 hi_95 cri_width\n  <chr> <dbl> <dbl>     <dbl>\n1 rt_05   968   976         8\n2 rt_10  1092  1103        11\n3 rt_15  1177  1203        26\n```\n\n\n:::\n:::\n\n\n## Reporting\n\n> We fitted a Bayesian Gaussian regression model with brms [@burkner2017] in R 4.5.0 [@rcoreteam2025]. The model had reaction times as the outcome variable and mean phone-level distance as the only predictor. The model was fitted with 4 MCMC chains and 2000 iterations per chains. The default brms priors were used.\n>\n> According to the model results, for every increase of mean phone-level distance by 1 unit, reaction times increase by 17-35 ms, at 95% probability (\\\\(\\\\beta\\\\) = 26.05, SD = 4.85). The 95% CrIs of the predicted reaction times at representative values of mean distance are: 968-976 ms for mean distance = 5, 1092-1103 ms for mean distance = 10, 1177-1203 for mean distance = 15.\n\n## References\n",
    "supporting": [
      "02_regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}