{
  "hash": "732c666d8be53b7b511011d710c10d5c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduction to Bayesian regression models\"\nsubtitle: \"01 - Basics\"\nauthor: \"Stefano Coretta\"\ninstitute: \"University of Edinburgh\"\neditor: source\nformat:\n  mono-light-revealjs:\n    theme: [default, custom.scss]\n    history: false\n    preview-links: true\nfilters:\n  - tachyonsextra\nexecute: \n  echo: true\nbibliography: references.bib\n---\n\n\n\n## Download the workshop materials\n\n::: box-error\n-   Download the workshop repository from: <https://github.com/stefanocoretta/learnBayes>.\n:::\n\n## Schedule\n\n| Times       | Topic                                 |\n|-------------|---------------------------------------|\n| 9.00-10.30  | Introduction to Bayesian modelling    |\n| 10.30-11.00 | *Break*                               |\n| 11.00-12.30 | Bayesian regression + Diagnostics     |\n| 12.30-14.30 | *Lunch break*                         |\n| 14.30-16.00 | Categorical predictors + Interactions |\n| 16.00-16.30 | *Break*                               |\n| 16.30-18.00 | Bayesian modelling Q&A                |\n\n## \n\n![](/img/One_Ring_inscription.svg.png){fig-align=\"right\" width=\"300\"}\n\n::: {.f2 style=\"text-align: right;\"}\nOne **model** to rule them all.<br> One **model** to find them.<br> One **model** to bring them all<br> And in the darkness bind them.\n:::\n\n. . .\n\n::: f5\n(No, I couldn't translate 'model' into Black Speech, alas...)\n:::\n\n## Now enter The Regression Model\n\n<p style=\"text-align:center\">\n\n<iframe src=\"https://giphy.com/embed/l4FGCymGGNTZVZwtO\" width=\"480\" height=\"200\" frameBorder=\"0\" class=\"giphy-embed\" allowFullScreen>\n\n</iframe>\n\n</p>\n\n## Now enter The Bayesian Regression Model\n\n<p style=\"text-align:center\">\n\n<iframe src=\"https://giphy.com/embed/3ov9jG4eqz9k3XXsU8\" width=\"480\" height=\"480\" frameBorder=\"0\" class=\"giphy-embed\" allowFullScreen>\n\n</iframe>\n\n</p>\n\n## All about the Bayes\n\n::: box-note\nWithin the **NHST (Frequentist) framework**, the main analysis output is:\n\n-   **Point estimates** of predictors' parameters (with standard error).\n-   ***p*****-values**.\n:::\n\n. . .\n\n::: box-warning\nSee @gigerenzer2004, @gigerenzer2004a, @gigerenzer2018 for problems with the \"Null Ritual\".\n:::\n\n. . .\n\n::: box-tip\nWithin the **Bayesian framework**, the main analysis output is:\n\n-   **Probability distributions** of predictors' parameters.\n:::\n\n## An example: MALD\n\n::: box-tip\n[Massive Auditory Lexical Decision](https://aphl.artsrn.ualberta.ca/?page_id=827) (MALD) data [@tucker2019]:\n\n-   **Auditory Lexical Decision task** with real and nonce English words.\n-   Reaction times and accuracy.\n-   Total 521 subjects; subset of 30 subjects, 100 observations each.\n:::\n\n## MALD data\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmald\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,000 × 7\n   Subject Item         IsWord PhonLev    RT ACC       RT_log\n   <chr>   <chr>        <fct>    <dbl> <int> <fct>      <dbl>\n 1 15345   nihnaxr      FALSE     5.84   945 correct     6.85\n 2 15345   skaep        FALSE     6.03  1046 incorrect   6.95\n 3 15345   grandparents TRUE     10.3    797 correct     6.68\n 4 15345   sehs         FALSE     5.88  2134 correct     7.67\n 5 15345   cousin       TRUE      5.78   597 correct     6.39\n 6 15345   blowup       TRUE      6.03   716 correct     6.57\n 7 15345   hhehrnzmaxn  FALSE     7.30  1985 correct     7.59\n 8 15345   mantic       TRUE      6.21  1591 correct     7.37\n 9 15345   notable      TRUE      6.82   620 correct     6.43\n10 15345   prowthihviht FALSE     7.68  1205 correct     7.09\n# ℹ 2,990 more rows\n```\n\n\n:::\n:::\n\n\n## MALD: phone-level distance and lexical status\n\nLet's investigate the effects of the following on Reaction Times (RTs):\n\n-   `PhonLev`: mean phone-level Levenshtein distance of the item from all other entries.\n    -   An alternative to neighbourhood density.\n-   `IsWord`: lexical status (real word vs nonce word).\n\n## \n\n```{=html}\n<iframe allowfullscreen frameborder=\"0\" height=\"600px\" mozallowfullscreen style=\"min-width: 500px; min-height: 355px\" src=\"https://app.wooclap.com/events/JEJPPA/questions/682f25c769100c24662fef2a\" width=\"100%\">\n\n</iframe>\n```\n\n## \n\n```{=html}\n<iframe allowfullscreen frameborder=\"0\" height=\"600px\" mozallowfullscreen style=\"min-width: 500px; min-height: 355px\" src=\"https://app.wooclap.com/events/JEJPPA/questions/682f260f776b2a0921ae54ed\" width=\"100%\">\n\n</iframe>\n```\n\n## MALD: phone-level distance and lexical status\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Scatter plot of mean phone-level distance vs reaction times.](01_basics_files/figure-revealjs/fig-dist-stat-1.png){#fig-dist-stat width=960}\n:::\n:::\n\n\n## A frequentist regression model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_1 <- lmer(\n  RT ~\n    PhonLev +\n    IsWord +\n    PhonLev:IsWord +\n    (1 | Subject),\n  data = mald\n)\n```\n:::\n\n\n## A frequentist regression model: summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: RT ~ PhonLev + IsWord + PhonLev:IsWord + (1 | Subject)\n   Data: mald\n\nREML criterion at convergence: 43232.4\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.5511 -0.5985 -0.2439  0.3185  5.6906 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Subject  (Intercept)  11032   105.0   \n Residual             104648   323.5   \nNumber of obs: 3000, groups:  Subject, 30\n\nFixed effects:\n                    Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)          754.965     49.687  862.751  15.195  < 2e-16 ***\nPhonLev               32.148      6.389 2970.933   5.032 5.15e-07 ***\nIsWordFALSE          212.440     65.453 2972.588   3.246  0.00118 ** \nPhonLev:IsWordFALSE  -11.620      9.076 2972.817  -1.280  0.20055    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) PhonLv IWFALS\nPhonLev     -0.907              \nIsWordFALSE -0.647  0.690       \nPhL:IWFALSE  0.640 -0.705 -0.983\n```\n\n\n:::\n:::\n\n\n## A frequentist regression model: plot predictions\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Reaction Times based on a frequentist regression model.](01_basics_files/figure-revealjs/fig-lm-1-pred-1.png){#fig-lm-1-pred width=960}\n:::\n:::\n\n\n## Increase model complexity\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_2 <- lmer(\n  RT ~\n    PhonLev +\n    IsWord +\n    PhonLev:IsWord +\n    (PhonLev*IsWord | Subject),\n  data = mald\n)\n```\n:::\n\n\n. . .\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nboundary (singular) fit: see help('isSingular')\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Model failed to converge with 1 negative eigenvalue: -2.5e+01\n```\n\n\n:::\n:::\n\n\n<p style=\"text-align:center\">\n\n<iframe src=\"https://giphy.com/embed/3o7abwbzKeaRksvVaE\" width=\"480\" height=\"204\" frameBorder=\"0\" class=\"giphy-embed\" allowFullScreen>\n\n</iframe>\n\n</p>\n\n## Let's go Bayesian! {background-color=\"var(--inverse)\"}\n\n![](/img/the-bayesian-rats.jpeg){fig-align=\"center\" width=\"500\"}\n\n## A Bayesian regression model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(brms)\n\nbrm_1 <- brm(\n  RT ~\n    PhonLev +\n    IsWord +\n    PhonLev:IsWord +\n    (PhonLev * IsWord | Subject),\n  data = mald,\n  family = gaussian()\n)\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## A Bayesian regression model: summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrm_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: RT ~ PhonLev + IsWord + PhonLev:IsWord + (PhonLev * IsWord | Subject) \n   Data: mald (Number of observations: 3000) \n  Draws: 4 chains, each with iter = 4000; warmup = 2000; thin = 1;\n         total post-warmup draws = 8000\n\nMultilevel Hyperparameters:\n~Subject (Number of levels: 30) \n                                     Estimate Est.Error l-95% CI u-95% CI Rhat\nsd(Intercept)                           89.60     32.39    23.91   163.00 1.00\nsd(PhonLev)                              6.81      4.93     0.32    17.93 1.00\nsd(IsWordFALSE)                        112.59     40.17    51.48   214.51 1.00\nsd(PhonLev:IsWordFALSE)                  6.49      5.27     0.22    19.83 1.00\ncor(Intercept,PhonLev)                  -0.31      0.44    -0.90     0.67 1.00\ncor(Intercept,IsWordFALSE)               0.43      0.29    -0.22     0.89 1.00\ncor(PhonLev,IsWordFALSE)                -0.19      0.44    -0.87     0.74 1.00\ncor(Intercept,PhonLev:IsWordFALSE)      -0.02      0.45    -0.82     0.82 1.00\ncor(PhonLev,PhonLev:IsWordFALSE)        -0.08      0.45    -0.84     0.78 1.00\ncor(IsWordFALSE,PhonLev:IsWordFALSE)    -0.30      0.47    -0.95     0.70 1.00\n                                     Bulk_ESS Tail_ESS\nsd(Intercept)                             928      371\nsd(PhonLev)                               750     1760\nsd(IsWordFALSE)                          1190      806\nsd(PhonLev:IsWordFALSE)                  1175      862\ncor(Intercept,PhonLev)                   2348     3006\ncor(Intercept,IsWordFALSE)               1012      661\ncor(PhonLev,IsWordFALSE)                  811     1085\ncor(Intercept,PhonLev:IsWordFALSE)       5085     3160\ncor(PhonLev,PhonLev:IsWordFALSE)         3771     3295\ncor(IsWordFALSE,PhonLev:IsWordFALSE)     1816     1348\n\nRegression Coefficients:\n                    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept             755.02     48.28   659.98   848.85 1.00     3920     5309\nPhonLev                31.99      6.52    18.99    44.79 1.00     4604     5222\nIsWordFALSE           208.23     67.99    75.34   341.44 1.00     3642     4658\nPhonLev:IsWordFALSE   -11.06      9.12   -28.68     6.71 1.00     3743     4748\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma   320.31      4.16   312.30   328.40 1.00     7998     5470\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n## A Bayesian regression model: plot predictions\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted RTs based on a Bayesian regression model.](01_basics_files/figure-revealjs/fig-brm-1-plot-1.png){#fig-brm-1-plot width=960}\n:::\n:::\n\n\n## Let's start small: A Gaussian model\n\n$$\nRT \\sim Gaussian(\\mu, \\sigma)\n$$\n\n-   Reaction Times $RT$\n\n-   distributed according to $\\sim$\n\n-   a Gaussian distribution $Gaussian()$\n\n-   with mean $\\mu$ and standard deviation $\\sigma$.\n\n. . .\n\n::: box-warning\nWe start with a Gaussian model for pedagogical reasons. You would usually start with the model you need to answer your research questions.\n:::\n\n## Uncertainty of parameters\n\n$$\n\\begin{align}\nRT & \\sim Gaussian(\\mu, \\sigma)\\\\\n\\mu & \\sim \\mathcal{P}(\\mu_1, \\sigma_1)\\\\\n\\sigma & \\sim \\mathcal{P}(\\mu_2, \\sigma_2)\n\\end{align}\n$$\n\n. . .\n\n::: box-note\n-   Uncertainty can be expressed with probability distributions. We use $\\mathcal{P}$ as a generic (undetermined) probability distribution.\n\n-   The Gaussian model estimates the probability distributions $\\mathcal{P}$ of $\\mu$ and $\\sigma$ from the data.\n\n-   These probability distributions $\\mathcal{P}$ are called **posterior probability distributions**.\n\n-   They can be summarised with $\\mu_1, \\sigma_1, \\mu_2, \\sigma_2$.\n:::\n\n## Gaussian model of RTs\n\n**Try it yourself!**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrm_2 <- brm(\n  # formula = \n  RT ~ 1,\n  data = mald,\n  # Specify the distribution family of the outcome\n  family = gaussian()\n)\n```\n:::\n\n\n. . .\n\n::: box-tip\n-   The model estimates the probability distributions of $\\mu$ and $\\sigma$.\n\n-   To do so, a **sampling algorithm** is used (Markov Chain Monte Carlo, **MCMC**).\n:::\n\n## MCMC what? {background-color=\"var(--inverse)\"}\n\n**Markov Chain Monte Carlo**\n\n-   MCMC simulation: <https://chi-feng.github.io/mcmc-demo/app.html>\n\n-   More on MCMC\n\n    -   <https://elizabethpankratz.github.io/bayes_stat/day1/mcmc.html>\n\n    -   <http://elevanth.org/blog/2017/11/28/build-a-better-markov-chain/>\n\n## Technicalities\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrm_2 <- brm(\n  RT ~ 1,\n  data = mald,\n  family = gaussian(),\n  \n  # TECHNICAL STUFF\n  # Save model output to file\n  file = \"./data/cache/brm_2.rds\",\n  # Number of MCMC chains\n  chains = 4, \n  # Number of iterations per chain\n  iter = 2000,\n  # Number of cores to use (one per chain)\n  cores = 4\n)\n```\n:::\n\n\n::: box-error\nYou can find out how many cores your laptop has with `parallel::detectCores()`.\n:::\n\n## The model summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrm_2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: RT ~ 1 \n   Data: mald (Number of observations: 3000) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept  1046.57      6.38  1034.21  1058.95 1.00     3165     2707\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma   347.57      4.52   338.77   356.50 1.00     3804     2833\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n## Interpret the summary: $\\mu$\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept  1046.57      6.38  1034.21  1058.95 1.00     3165     2707\n```\n\n\n:::\n:::\n\n\n::: box-warning\n`Intercept` is $\\mu$.\n\n$$\n\\begin{align}\nRT & \\sim Gaussian(\\mu, \\sigma)\\\\\n\\mu & \\sim \\mathcal{P}(1046.57, 6.38)\\\\\n\\end{align}\n$$\n\n-   The posterior probability distribution of $\\mu$, i.e. of the mean RTs, is $\\mathcal{P}(1047, 6)$.\n\n-   There is a **95% probability** that the mean RTs is **between 1034 and 1059 ms**, conditional on the model and data. This is the 95% Credible Interval (CrI) of $\\mathcal{P}(1047, 6)$.\n:::\n\n## Interpret the summary: $\\sigma$\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma   347.57      4.52   338.77   356.50 1.00     3804     2833\n```\n\n\n:::\n:::\n\n\n::: box-warning\n`sigma` is $\\sigma$.\n\n$$\n\\begin{align}\nRT & \\sim Gaussian(\\mu, \\sigma)\\\\\n\\mu & \\sim \\mathcal{P}(1046.57, 6.38)\\\\\n\\sigma & \\sim \\mathcal{P}(347.57, 4.52)\n\\end{align}\n$$\n\n-   The posterior probability distribution of $\\sigma$, i.e. of the standard deviation of RTs, is $\\mathcal{P}(348, 5)$.\n\n-   There is a **95% probability** that the RT standard deviation is **between 339 and 357 ms**, conditional on the model and data.\n:::\n\n## Posterior probabilities\n\n::: box-note\n-   These are **posterior probability distributions**.\n-   They are always conditional on model and data.\n-   The summary reports **95% Credible Intervals (CrIs)**, but there is nothing special about 95% and you should obtain a set of intervals.\n:::\n\n## Model plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(brm_2, combo = c(\"dens\", \"trace\"))\n```\n\n::: {.cell-output-display}\n![Density and trace plot of the Bayesian Gaussian model `brm_2`.](01_basics_files/figure-revealjs/fig-brm-2-plot-1.png){#fig-brm-2-plot width=960}\n:::\n:::\n\n\n## Extract the MCMC draws\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrm_2_draws <- as_draws_df(brm_2)\nbrm_2_draws\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A draws_df: 1000 iterations, 4 chains, and 5 variables\n   b_Intercept sigma Intercept lprior   lp__\n1         1046   348      1046    -13 -21816\n2         1052   353      1052    -13 -21817\n3         1039   349      1039    -13 -21817\n4         1045   343      1045    -13 -21817\n5         1046   344      1046    -13 -21817\n6         1050   348      1050    -13 -21816\n7         1050   348      1050    -13 -21816\n8         1044   345      1044    -13 -21816\n9         1048   350      1048    -13 -21816\n10        1036   345      1036    -13 -21818\n# ... with 3990 more draws\n# ... hidden reserved variables {'.chain', '.iteration', '.draw'}\n```\n\n\n:::\n:::\n\n\n## Get parameters\n\nTo list all the names of the parameters in a model, use:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvariables(brm_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"b_Intercept\" \"sigma\"       \"Intercept\"   \"lprior\"      \"lp__\"       \n```\n\n\n:::\n:::\n\n\n## Posterior distribution: mean RT\n\nNow you can plot the probability density of the draws using ggplot2.\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nbrm_2_draws |>\n  ggplot(aes(b_Intercept)) +\n  geom_density(fill = \"#214d65\", alpha = 0.8) +\n  labs(title = \"Posterior distribution of mean RT\")\n```\n\n::: {.cell-output-display}\n![](01_basics_files/figure-revealjs/brm-2-mean-1.png){width=960}\n:::\n:::\n\n\n## Posterior distribution: sigma\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nbrm_2_draws |>\n  ggplot(aes(sigma)) +\n  geom_density(fill = \"#1F6357\", alpha = 0.8) +\n  labs(title = \"Posterior distribution of the SD\")\n```\n\n::: {.cell-output-display}\n![](01_basics_files/figure-revealjs/brm-2-sigma-1.png){width=960}\n:::\n:::\n\n\n## Summary\n\n::: box-note\n-   Bayesian statistics is a **framework for doing inference** (i.e. learning something about a population from a sample).\n\n-   The Bayesian framework is based on **estimating uncertainty with probability distributions** on parameters.\n\n-   The **syntax** you know from `[g]lm[er]()` works with `brm()` from the brms package.\n\n-   Results allow you to make statements like \"There is a 95% probability that the difference between A and B is between *q* and *w*\".\n:::\n\n## References\n",
    "supporting": [
      "01_basics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}